MVC/Controllers/ListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVC.Controllers
{
    public class ListController : Controller
    {
        public static List<person> p = new List<person>() {
             new person {id=1,name="zhangsan",address="henan" },
             new person {id=2,name="zhangsan",address="henan" },
         };
           // GET: List
        public ActionResult Index()
        {
           

            return View(p);
        }
        public ActionResult Add()
        {

            return View();
        }
        public ActionResult AddData(int uid,string uname,string uaddress)
        {
            p.Add(new person()
            {
                id = uid,
                name = uname,
                address = uaddress
            });
            return RedirectToAction("index");
        }
        public ActionResult delete(int id)
        {
           var y= p.First(x => x.id == id);
            p.Remove(y);
            return RedirectToAction("index");
        }
        public ActionResult edit(int id)
        {
           var j = p.First(c => c.id == id);
            
            return View (j);

        }
        public ActionResult editdata(int uid,string uname,string uaddress)
        {
            person j = p.First(c => c.id == uid);
            j.name = uname;
            j.address = uaddress;
            return RedirectToAction("index");
        }
    public class person
    {
            public int id { get; set; }
            public string name { get; set; }
            public string address { get; set; }
        }
    }
}

MVC/Views/List/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <table>
          <tr>
              <th>编号</th><th>名称</th><th>地址</th><th>编辑</th><th>删除</th>
          </tr>
            @foreach (var item in Model )
            {
                <tr><td>@item.id</td><td>@item.name</td><td>@item.address</td><td><a href="/List/edit/@item.id">编辑</a></td><td><a href="/List/delete/@item.id">删除</a></td></tr>
            }
        </table>
       <a href="List/Add">添加</a>
    </div>
</body>
</html>

MVC/Views/List/add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>add</title>
</head>
<body>
    <div> 
        <form method="post" action="/List/AddData">
            编号：<input type="text" name="uid" />
            名称：<input type="text" name="uanme" />
            地址：<input type="text" name="uaddress" />
            <input type="submit" value="确定" />
        </form>
    </div>
</body>
</html>

MVC/Views/List/edit.cshtml
@{
    Layout = null;
}
@using MVC.Controllers
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>edit</title>
</head>
<body>
    <div> 
        <form method="post" action="@Url.Action("editdata","List")">
            编号：<input type="text" name="uid"  value="@Model.id"/>
            名称：<input type="text" name="uanme"  value="@Model.name"/>
            地址：<input type="text" name="uaddress" value="@Model.address" />
            <input type="submit" value="修改" />
        </form>
    </div>
</body>
</html>