htmlDemo/Models/Course.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.Score = new HashSet<Score>();
        }
    
        public int cid { get; set; }
        public string cname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
    }
}

htmlDemo/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentTestEntities : DbContext
    {
        public StudentTestEntities()
            : base("name=StudentTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Course { get; set; }
        public virtual DbSet<Score> Score { get; set; }
        public virtual DbSet<StudentInfo> StudentInfo { get; set; }
    }
}

htmlDemo/Models/Model1.Designer.cs
// 为模型“E:\计算机基础\大三\解决方案\MVC\htmlDemo\Models\Model1.edmx”启用了 T4 代码生成。
// 要启用旧代码生成功能，请将“代码生成策略”设计器属性的值
// 更改为“旧的 ObjectContext”。当在设计器中打开该模型时，此属性会出现在
// “属性”窗口中。

// 如果没有生成任何上下文和实体类，可能是因为您创建了空模型但是
// 尚未选择要使用的实体框架版本。要为您的模型生成一个上下文类和实体
// 类，请在设计器中打开该模型，右键单击设计器图面，然后
// 选择“从数据库更新模型...”、“从模型生成数据库...”或“添加代码生成
// 项...”。

htmlDemo/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

htmlDemo/Models/Score.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Score
    {
        public int sid { get; set; }
        public int cid { get; set; }
        public int course { get; set; }
    
        public virtual Course Course1 { get; set; }
        public virtual StudentInfo StudentInfo { get; set; }
    }
}

htmlDemo/Models/StudentInfo.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace htmlDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentInfo()
        {
            this.Score = new HashSet<Score>();
        }
    
        public int sid { get; set; }
        public string sname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Score> Score { get; set; }
    }
}

htmlDemo/Models/person.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace htmlDemo.Controllers
{
    public class person
    {
        [Required(ErrorMessage ="不能为空")]
        [StringLength(20,MinimumLength =5,ErrorMessage ="名称长度为5到20之间")]
        public string  name { get; set; }
        [RegularExpression(@"\d+",ErrorMessage ="密码必须是数字")]
        public string  pwd { get; set; }
    }
}

htmlDemo/Controllers/AjaxController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace htmlDemo.Controllers
{
    public class AjaxController : Controller
    {
        // GET: Ajax
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult add(int id,string name, int age)
        {
            return Content("姓名：" + name + "编号" + id + "年龄：" + age);
        }
        public ActionResult add1( string name, string  pwd)
        {
            return Content("姓名：" + name + "密码："+pwd);
        }
    }
}

htmlDemo/Controllers/DefaultController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace htmlDemo.Controllers
{
    public class DefaultController : Controller
    {
        // GET: Default
        public ActionResult Index()
        {
            return View();
        }
    }
}

htmlDemo/Controllers/yanzhengController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace htmlDemo.Controllers
{
    public class yanzhengController : Controller
    {
     public static    List<person> lp = new List<person>();
        // GET: yanzheng
        public ActionResult Index()
        {
            return View(lp );
        }
        public ActionResult add()
        {
            return View();
        }
        public ActionResult adddata(person p)
        {
            person pp = new Controllers.person();
            p.name = pp.name;
            p.pwd = pp.pwd;
            lp.Add(pp);
            return RedirectToAction("index");
        }
    }
}

htmlDemo/Views/Ajax/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/sc/jquery-1.8.0.js"></script>
    <script src="~/sc/jquery.unobtrusive-ajax.js"></script>
    <script>
        $(function () {
            $("#btn").click(function () {
               
            })
        })
    </script>
</head>
<body> 
    <div>
        @*ajax 作用就是无刷新界面   不管是按钮或表单提交   都是把信息提交到本界面中*@
        @using (Ajax.BeginForm("add", "ajax", new AjaxOptions()
            {
                HttpMethod = "post",
                UpdateTargetId = "div1",
                InsertionMode = InsertionMode.InsertAfter

        }))
        {
        @:id<input type="text" name="id" />
        @:name<input type="text" name="name" />
        @:age<input type="text" name="age" />
        <input type = "submit" value = "提交" />
        }
    </div>
  
    <div id="div1"> 
        <h1>阿加西</h1>
    </div>
    <form >
        姓名：<input type="text" name="name" />
        密码：<input type="text" name="pwd" />
        <input type="submit"  value="提交" id="btn"/>
    </form>
   
</body>
</html>

htmlDemo/Views/Default/Index.cshtml
@model IEnumerable<htmlDemo.Models.Course>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.cid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.cname)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.cid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.cname)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

htmlDemo/Views/yanzheng/Index.cshtml
@model IEnumerable<htmlDemo.Controllers.person>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.8.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body>
    <p>
        @Html.ActionLink("添加", "add")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.pwd)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.pwd)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

htmlDemo/Views/yanzheng/add.cshtml
@model htmlDemo.Controllers.person

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>add</title>
</head>
<body>
    @using (Html.BeginForm("adddata","yanzheng",FormMethod.Post )) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>person</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.pwd, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.pwd, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.pwd, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>