MVC/Controllers/CoureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVC.Models;
namespace MVC.Controllers
{
    public class CoureController : Controller
    {
        StudentTestEntities1 stu = new StudentTestEntities1();
        // GET: Coure
        public ActionResult Index()
        {
            var  s = from c in stu.Course
                            select c;
            return View(s);
        }
        /// <summary>
        /// 添加
        /// </summary>
        /// <returns></returns>
       public ActionResult add()
        {
            return View();
        }
        public ActionResult adddata(FormCollection fm)
        {
            Course c = new Course();
            c.cname = fm["name"];
            stu.Course.Add(c);
            //stu.Configuration.ValidateOnSaveEnabled = false;
            stu.SaveChanges();
            return RedirectToAction("index");
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult delete(int id)
        {
            var d = (from dd in stu.Course
                     where dd.cid == id
                     select dd).First();
            stu.Course.Remove(d);
            stu.SaveChanges();
            return RedirectToAction("index");
        }
        public ActionResult edit(int id, string name)
        {
            var a = (from dd in stu.Course
                     where dd.cid == id
                     select dd).First();
            ViewData["cname"] =a.cname;
            ViewData["cid"] = a.cid;
            return View(a);
           
        }
        public ActionResult editdata(int cid,string cname)
        {
            var a = (from dd in stu.Course
                     where dd.cid == cid
                     select dd).First();
            a.cid = cid;
            a.cname = cname;
            //stu.Configuration.ValidateOnSaveEnabled = false;
            stu.SaveChanges();
            return RedirectToAction("index");
        }
    }
}

MVC/Views/Coure/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <form>
            <table>
                <tr><td>编号</td><td>课程名称</td><td>编辑</td><td>删除</td></tr>
                @foreach (var item in Model)
                {
                    <tr><td>@item.cid</td><td>@item.cname</td><td>@Html.ActionLink("编辑", "edit", new { id = item.cid })</td>@*<td><a href="/Student/delete/@item.sid">删除</a></td>*@<td>@Html.ActionLink("删除", "delete", new { id = item.cid })</td></tr>
                }
            </table>
            @Html.ActionLink("添加", "add")
        </form> 
    </div>
</body>
</html>

MVC/Views/Coure/add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>add</title>
</head>
<body>
    <div> 
        <form method="post" action="@Url.Action("adddata","Coure")">
            课程名称：<input type="text" name="name" />
            <input type="submit" value="确定" />
        </form> 
    </div>
</body>
</html>

MVC/Views/Coure/edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>edit</title>
</head>
<body>
    <div> 
        <form method="post" action="@Url.Action("editdata","Coure")">
            编号：<input type="text" name="cid" value="@Model.cid" ]" disabled="disabled" />
            课程名称：<input type="text" name="cname" value="@Model.cname" ]" />
            <input type="submit" value="确定" />
        </form> 
    </div>
</body>
</html>